"""Initial migration

Revision ID: 63ce28e6f70e
Revises: None
Create Date: 2016-08-10 09:32:58.785158

"""

# revision identifiers, used by Alembic.
revision = '63ce28e6f70e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
